= 2024
== Text 1
#grid(
  columns: (1.1fr, 1fr),
  gutter: 18pt,
  [Nearly 2,000 years ago, as the Romans began to pull out of Scotland, they left behind a curious treasure: 10 tons of nails, nearly a million of them.],
  [],
  [The nail hoard was discovered in 1960 in a four-meter-deep pit covered by two meters of gravel.],
  [],
  [Why had the Romans buried a million nails?],
  [],
  [The likely explanation is that the withdrawal was rushed, and they didn't want the local Caledonians getting their hands on 10 tons of weapons-grade iron.],
  [],
  [The Romans buried the nails so deep that they would not be discovered for almost two millennia.],
  [],
  [Later civilizations would value the skilled blacksmith's labor in a nail even more than the raw material.],
  [],
  [As Roma Agrawal explains in her new delightful book "Nuts and Bolts," early 17th-century Virginians would sometimes burn down their homes if they were planning to relocate.],
  [],
  [This was an attempt to recover the valuable nails, which could be reused after sifting the ashes.],
  [],
  [The price of nails fell by 90% between the late 1700s and mid-1900s, as economist Daniel Sidel points out in a research paper.],
  [],
  [According to Sidel, although the falling price of nails was driven partly by cheaper iron and cheaper energy, most of the credit goes to nail manufacturers who simply found more efficient ways to turn steel into nails.],
  [],
  [Nails themselves have changed over the years, but Sidel studied them because they haven't changed much.],
  [],
)